name: Unit tests
on:
  push:
    branches:
      - main
jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache purescript dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .spago
            ${{ env.spago_global_cache }}
            output
          key: >-
            ${{ hashFiles('package-lock.json') }}-
            ${{ hashFiles('spago.dhall') }}-
            ${{ hashFiles('packages.dhall') }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
